# Build stage
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ENV DATABASE_URL="postgresql://user:password@db:5432/dbname"

RUN npx prisma generate

RUN npm run build

# Final image
FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd

COPY --from=builder /app ./

COPY wait-for-db.sh ./wait-for-db.sh
#RUN chmod +x wait-for-db.sh
RUN sed -i 's/\r$//' ./wait-for-db.sh
RUN chmod +x ./wait-for-db.sh

EXPOSE 3000

CMD ["sh", "-c", "./wait-for-db.sh db 5432 \"npx prisma migrate deploy && npx prisma db seed && npm run start\""]




